
from monitoring.models import Santri


# Hapus data lama agar bersih

Santri.objects.all().delete()


data_kelas = {

    "XA": "ABDUL HAAMID,ALIF WARDHANI SANTOSO,ALVARO SYARIF FERYANSYAH,ARKAN SYAIBANU SOFYAN,ARKANSYAH NAKHLAN ZAKARIA,AZKA IRHAM PURWANSYAH,AZZAM DZAKWAN AL FARUQ,DAVA KEANU PUTRA,EL FAYAADH,FAIZ HAQIQI,GALYZVITO DWIYANDRA,HABIBURRAHMAN AL HASYIM,HAFIZ KIYOSHI ARIF,HASAN,HUDZAIFAH AL HUMAIDI,LYAS MUSTHAFA AKHYAR,IRFANDA ADHA MIRZALI,KENNARD DZAKI HERLAMBANG,LUQMAN ABDUL HAKIM,MOHAMMAD AL KAUTSAR,MOHAMMAD ARSYAD NARARYA PRATOMO,MUHAMMAD AL - FATIH,MUHAMMAD AYYASH GHAZI MIFZAL,MUHAMMAD BINTANG PUTRARASYA,MUHAMMAD FADHIL AZKARA,NOUVAL RASYDAN ENDRI,RAQOIS FAWWAZ BAARI'UL MUMTAAZ,RANJANA MUMTAZ ATHALLAH,ZIDANE",

    "XB": "ABDULLAH MUHAMMAD RAHMAN,AFFAN FIRDAUS,AHMAD DANI,AKHDAN HELMI,AMMAAR ZAKKY BATHHEF,ANAS WILDAN SOBARI,ARIF KHAIRUL AZAM,ATILLA DHIYAEL FAJRI,BINTANG ALFIANO BRILIANT SAPUTRA,DARU AZRI ARMANSYAH,FA'IQ,FAKHRY MUHAMMAD RAYYAN,FAUZAN HUSEIN BADJRY,HAFIDZ KHALFANI HAMISENA,HANIF ALFARIZI,KEANU AL GHIFARI AHMAD JAEPUTRA,LUQMANUL HAKIM ADDATIN,MOCH. REYZA SYARIF ABIDIN,MUCHAMMAD THORIQ AL MUZACKY,MUHAMMAD FATHURRAHMAN,MUHAMMAD NATHAN AL FAIQ,MUHAMMAD RASYID,MUSH'AB UMAIR ZACHA WERUS,RAYZA FIDIANO SIREGAR,SAMI RABBANI HARTONO,UBAIDAH AS SA'DY,UMAR MUBARAK,ZIYAD GHASSAN AZRI SASONO",

    "XC": "AHMAD HARIS IKHWAN,AHMAD TSABIT,ANDRA AIDILLAH,ARAFAH ZHILLAN AMIR NASUTION,AUFA SAKHA SALMAN,AZFAR IRHAM PURWANSYAH,DARRELL YUSRAN ILMANY RAFAN,FAIZ ABDUL AZIZ,FARRAS MUHAMMAD RAMADHAN,FATHI RAYA NONCI,GAVIN EKISA AQILA FIKRA,GHILMAN ADZKA SYUHADA,KHALISMAN RAMADHAN,LUQMAN HAFIDZ ANNURIL HIDAYAT,MIQDAD,MUHAMMAD ALIFFATTAH AS-SYIFA' SUYANTOM,MUHAMMAD AMMAR NUFAIL,MUHAMMAD FA'IQ FAYYADH QUSHAYYI,MUHAMMAD NABIL MAKARIM,MUHAMMAD RAFIIF GATHFAN,MUHAMMAD SETYO ABDUN NASTIR,MUHAMMAD TEGUH HASAN,MUHAMMAD TIFATULLAH ARRASYID ISMAIL,RAIKHAN RASHEED DZAKIANSYAH,TENGKU MUADZ,UWAIS UBAIDILLAH,YAVI AL'FIAN CHRISTIANDY",

    "XD": "AHMAD HANIF FAUZAN,AHNAF FARRAS JATMIKA,ARKAN UMAIR ROFIF,ARKANANTA RA'UUF BAADILLA,ATHASYAH REIZKI RAMADHAN,AZZAM BAWAZIER,BRAMANTYO PURWOKO NURINGDAVIANDRA JULIAN SISWOYO,DHEVIN ADELIO TAMAM,ELMALIK ANANDYA SOFYAN,FAWAAZ KARIIM BENZEMA,GHAISAN ALTHAF NAZURAKHADAFI FAHRIANSYAH,M YUSUP,MAUZA YUSUF RAFFASYA,MUHAMMAD BINAR PRAWISENO,MUHAMMAD FADHIL KHAIRULLAH,MUHAMMAD FAREL ISVIKHRAM,MUHAMMAD RASHID RIZWAAN,MUHAMMAD RHAMDHANI EL HAQQ,NAUFAL FAWWAZ ALFIAN,RADEN MIKAIL HAFIZH GOENAWAN,RAFA DLAIFURRAHMAN FAHAMSYAH,RAFI MUHAMAD RIZQI,SALMAN ALI,SHAQUILLE MUFTY KASYAFANI,SULAEMAN HARUN MAR'IZIGGY ALVA RADZAVIER",

    "XE": "ADKHILNI MUDKHALA SIDQI,ARKAAN ABDILLAH PRANAAWALIAH,ARKHAREGA RADITHYA NARARYA AGUSTIAN,ATHAYA SHABRAZAN ADHSY,AZZAM SHIDIQ NURYANTO,DAFFA TRISTAN ADINATA KHRISNADIYANTO,DAFFI HADI YURIAWAN,DASTAN ZAHIR MANAF,DZAKY ALMER RAFIF,FARZAN FAEYZA RAVIDYATAMA,FATHAN ZIDANE ATTAYA,HAMDY MOHAMMAD GHOSAN,HAZZA IRSA ASWATAMA,MUHAMAD ATHADZAKI UKASYAH ZAENAL,MUHAMMAD DZUL HABIE MUKTIADIM,MUHAMMAD FARIS HUMAM,MUHAMMAD MULTAZAM AL GHAZALIPARAMA RAISSA OBADIAH,QAISHAR FADHIL DZIHNI,R. MUHAMMAD TERZAGHI INDRA HERMAWAN,REYHAN FADHLILLAH PANGESTURHAFAEL FATURAHMAN,RYANDRA PUTRA RIFAI,SA'AD ALI,SYED AHMAD ZAKY ABDURAHMAN,THUFAIL MUHAMMAD KHALIDI,THUFEIL TSANI AR-ROYYAN",

    "XF": "ABRISAM TRYSTAN AL-LYADI,ALTAF ADLI ARYASATYA,AMRU ABDUL FATTAH,ARYAN MIKA USAID,AULIA ABDURRAHMAN RAFIUDDIN,DANISH MUMTAAZ AHMAD,DEWA ANUGERAH SUNARTO,DZIKRA AQSHA RAMADHAN,FAIDHUL KHOIR,FARREL RASYA FAUZI,GHAZI MAGHRIBI FATHUL MAKKI,HASAN RAFA AQILAH,IBNU JAMIL MAJIDI,IHSAN MAULANA KEANDRE,MIKHAIL ALFATIH HADINA,MUHAMMAD DENDY JUNSEN DUOVAN,MUHAMMAD FACHRI ANGGARA,MUHAMMAD NAZRIL BAIHAQI,MUHAMMAD RAFA CAKSONO,MUHAMMAD RIFQI,MUHAMMAD SYAUQI ABRAR,RADITYA ABDI WIENATARANGGA ADYATMA BRAMANTYORAYYAN MALIK ARYASATYASULTHAN ALTHAF OHINPUTRA RAHIM,ZAHRAN DZIAULHAQ KAMIL,ZHAFIR KHALISH AL MASY'AL"

}


for k, v in data_kelas.items():

    for nama in v.split(","):

        Santri.objects.create(nama=nama.strip(), kelas=k, induk=f"{k}-{nama.strip()[:10]}")


print("--- INPUT DATA SELESAI ---")

