# Generated by Django 5.2.12 on 2026-04-07 01:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('induk', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaporanBacaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('halaman_awal', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604)])),
                ('halaman_akhir', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604)])),
                ('durasi_menit', models.PositiveIntegerField(default=30)),
                ('catatan', models.TextField(blank=True)),
                ('ustaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.santri')),
            ],
        ),
    ]
