# Generated by Django 5.2.12 on 2026-04-09 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_laporanbacaan_halaman_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporanbacaan',
            name='halaman_akhir',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604)]),
        ),
        migrations.AlterField(
            model_name='laporanbacaan',
            name='halaman_awal',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604)]),
        ),
        migrations.AlterField(
            model_name='laporanbacaan',
            name='halaman_target',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(604)]),
        ),
        migrations.AlterField(
            model_name='laporanbacaan',
            name='tanggal',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='laporanbacaan',
            unique_together={('santri', 'tanggal')},
        ),
    ]
