# Generated by Django 5.2.12 on 2026-04-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_laporanbacaan_halaman_akhir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporanbacaan',
            name='durasi_menit',
        ),
        migrations.AddField(
            model_name='laporanbacaan',
            name='jumlah_khatam',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laporanbacaan',
            name='status_kehadiran',
            field=models.CharField(choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpa', 'Alpa')], default='Hadir', max_length=10),
        ),
        migrations.AddField(
            model_name='santri',
            name='kelas',
            field=models.CharField(choices=[('XA', 'XA'), ('XB', 'XB'), ('XC', 'XC'), ('XD', 'XD'), ('XE', 'XE'), ('XF', 'XF'), ('XIA', 'XIA'), ('XIB', 'XIB'), ('XIC', 'XIC'), ('XID', 'XID'), ('XIE', 'XIE'), ('XIIA', 'XIIA'), ('XIIB', 'XIIB'), ('XIIC', 'XIIC'), ('XIID', 'XIID'), ('XIIE', 'XIIE')], default='XA', max_length=5),
        ),
        migrations.AlterField(
            model_name='laporanbacaan',
            name='halaman_akhir',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laporanbacaan',
            name='halaman_awal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laporanbacaan',
            name='halaman_target',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
